### ISSUE TITLE
`check()` runs twice for components directly under the `Test`

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd-vf#45]
### Describe the bug

This code is in test.dart:
```dart
  void _checkAll() {
    final checkQueue = Queue.of([this, ...components]);
    while (checkQueue.isNotEmpty) {
      final component = checkQueue.removeFirst();
      checkQueue.addAll(component.components);
      component.check();
```

The `components` of `Test` (`this`) get added twice to the `checkQueue`, causing `check()` to be called twice.

### To Reproduce

Implement a severe/fatal check in a component directly under `Test`

### Expected behavior

`check()` only runs once

### Actual behavior

`check()` runs twice

**Comment by MehanathanS** [comment]
I can work on this
